name: Jennifer Engel
favicon: null
layout_spectrum: 0.6084361290559173
typography_spectrum: 0.9590491256676614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8064149122219533
  lightness: 0.829179871128872
  saturation: 0.7918135568033904
  rhythmicContrast: 0.9585503255948424
purpose: []
